// Zah Bookstore — katalog demo. Data buku diambil dari halaman resmi Penerbit Qaf
// (penerbitqaf.com) pada 2026-08-10: judul, ISBN, tebal, dimensi, bulan terbit, harga, sinopsis.
window.BOOKS = [
  {
    slug: "memahami-surah-al-maun",
    forWho: "Untuk yang ingin ibadah berdampak sosial",
    cat: "surah",
    title: "Memahami Surah Al-Ma'un",
    sub: "Tujuh Pesan Penerang Hidup",
    isbn: "978-634-04-5902-9",
    pages: 166,
    dim: "13 × 19 cm",
    year: "Januari 2026",
    price: 45000,
    tag: "Terbaru",
    cover: "img/memahami-surah-al-maun.jpg",
    src: "https://penerbitqaf.com/product/memahami-surah-al-maun/",
    blurb: "Sekalipun singkat, pesan al-Ma‘un amatlah padat — pelajaran berharga soal keimanan, keislaman, dan kesucian hati. Surah yang menggugah kita menempatkan Al-Qur’an sebagai kitab pengubah zaman, dan menjadikan keberpihakan pada kaum lemah sebagai tolok ukur keyakinan yang benar."
  },
  {
    slug: "ilmu-ikhlas",
    forWho: "Untuk yang hatinya mudah gelisah",
    cat: "hati",
    title: "Ilmu Ikhlas",
    sub: "Belajar Membeningkan Hati dan Membahagiakan Hidup dari Ulama Psikolog-Klasik",
    isbn: "978-623-1099-63-1",
    pages: 184,
    dim: "13 × 20,5 cm",
    year: "Juni 2025",
    price: 49500,
    tag: "Best Seller",
    cover: "img/ilmu-ikhlas.jpg",
    src: "https://penerbitqaf.com/product/ilmu-ikhlas/",
    blurb: "Buku tentang ilmu ikhlas — ilmu rahasia yang menjadi kunci kebahagiaan, yang tak banyak orang menyelami hakikatnya. Dari menata niat, menakar ikhlas, hingga puncak ikhlas: derajat mukhlish dan mukhlash."
  },
  {
    slug: "memahami-surah-al-fatihah",
    forWho: "Untuk pemula yang baru belajar tafsir",
    cat: "surah",
    title: "Memahami Surah Al-Fatihah",
    sub: "Makna dan Pesan yang Terukir dengan Beragam Manhaj Tafsir",
    isbn: "978-623-6219-95-9",
    pages: 176,
    dim: "13 × 19 cm",
    year: "Oktober 2024",
    price: 45000,
    tag: "Pilihan Pembaca",
    cover: "img/memahami-surah-al-fatihah.jpg",
    src: "https://penerbitqaf.com/product/memahami-surah-al-fatihah/",
    blurb: "Saking seringnya dibaca, makna al-Fatihah kerap luput dari perhatian. Buku ini menemani pembaca menyelami keindahan maknanya serta merasakan berkahnya bagi hati dan kehidupan nyata."
  },
  {
    slug: "rizqan-wasian-thayyiban",
    forWho: "Untuk yang gelisah soal rezeki",
    cat: "hati",
    title: "Rizqan Wasi'an Thayyiban",
    sub: "Tuntunan Ulama Klasik untuk Meraih Rezeki yang Luas dan Hidup yang Lebih Puas",
    isbn: "978-623-6219-89-8",
    pages: 193,
    dim: "13 × 20,5 cm",
    year: "September 2024",
    price: 54000,
    tag: "Kearifan Klasik",
    cover: "img/rizqan-wasian-thayyiban.jpg",
    src: "https://penerbitqaf.com/product/rizqan-wasian-thayyiban/",
    blurb: "Menyegarkan pola pikir tentang rezeki yang terus mengalir. Pengantar tentang bagaimana mengharap rezeki yang lancar dengan sikap hati yang benar — rezeki yang luas, hidup yang lebih puas, di atas fondasi keimanan yang pas."
  },
  {
    slug: "tafsir-bacaan-shalat",
    forWho: "Untuk yang ingin shalat lebih khusyuk",
    cat: "shalat",
    title: "Tafsir Bacaan Shalat",
    sub: "Hati Sejuk Ibadah Khusyuk",
    isbn: "978-623-6219-92-8",
    pages: 196,
    dim: "13 × 20,5 cm",
    year: "September 2024",
    price: 54000,
    tag: "Paling Dicari",
    cover: "img/tafsir-bacaan-shalat.jpg",
    src: "https://penerbitqaf.com/product/tafsir-bacaan-shalat/",
    blurb: "Belajar meningkatkan kualitas shalat dengan menyelami makna dan pesan dalam bacaan shalat — dari takbiratul ihram hingga salam."
  },
  {
    slug: "memahami-surah-yasin",
    forWho: "Untuk yang rutin membaca Yasin",
    cat: "surah",
    title: "Memahami Surah Yasin",
    sub: "Dengan Metode Tafsirul-Qur'an bil-Qur'an",
    isbn: "978-602-5547-53-9",
    pages: 272,
    dim: "13 × 19 cm",
    year: "Maret 2019",
    price: 53100,
    tag: "Klasik Modern",
    cover: "img/memahami-surah-yasin.jpg",
    src: "https://penerbitqaf.com/product/memahami-surah-yasin/",
    blurb: "Surah Yasin sudah sering dibaca dan dihafal. Namun sudahkah kita menyelami makna dan pesannya? Ditafsirkan dengan metode menafsirkan Qur’an dengan Qur’an."
  }
];
window.BUNDLE = {
  slug: "paket-5-buku-dr-izza-rohman",
  title: "Paket 5 Buku Dr. Izza Rohman",
  price: 247500,
  cover: "img/paket-5-buku-dr-izza-rohman.jpg",
  src: "https://penerbitqaf.com/product/paket-5-buku-dr-izza-rohman/",
  items: ["Tafsir Bacaan Shalat", "Rizqan Wasi'an Thayyiban", "Memahami Surah Al-Fatihah", "Ilmu Ikhlas", "Memahami Surah Al-Ma'un"],
  bonus: "Bonus 1 judul — Memahami Surah Yasin"
};
