/* 114 surah — accurate metadata only (no tafsir text invented).
   n=urut, ar=nama Arab, tr=transliterasi, id=arti (ID), type=Makkiyah/Madaniyah, ayat=jumlah ayat */
const SURAHS = [
 {n:1,ar:'الفاتحة',tr:'Al-Fatihah',id:'Pembukaan',type:'Makkiyah',ayat:7},
 {n:2,ar:'البقرة',tr:'Al-Baqarah',id:'Sapi Betina',type:'Madaniyah',ayat:286},
 {n:3,ar:'آل عمران',tr:"Ali 'Imran",id:'Keluarga Imran',type:'Madaniyah',ayat:200},
 {n:4,ar:'النساء',tr:"An-Nisa'",id:'Wanita',type:'Madaniyah',ayat:176},
 {n:5,ar:'المائدة',tr:'Al-Ma\'idah',id:'Hidangan',type:'Madaniyah',ayat:120},
 {n:6,ar:'الأنعام',tr:'Al-An\'am',id:'Binatang Ternak',type:'Makkiyah',ayat:165},
 {n:7,ar:'الأعراف',tr:'Al-A\'raf',id:'Tempat Tertinggi',type:'Makkiyah',ayat:206},
 {n:8,ar:'الأنفال',tr:'Al-Anfal',id:'Rampasan Perang',type:'Madaniyah',ayat:75},
 {n:9,ar:'التوبة',tr:'At-Taubah',id:'Pertobatan',type:'Madaniyah',ayat:129},
 {n:10,ar:'يونس',tr:'Yunus',id:'Nabi Yunus',type:'Makkiyah',ayat:109},
 {n:11,ar:'هود',tr:'Hud',id:'Nabi Hud',type:'Makkiyah',ayat:123},
 {n:12,ar:'يوسف',tr:'Yusuf',id:'Nabi Yusuf',type:'Makkiyah',ayat:111},
 {n:13,ar:'الرعد',tr:'Ar-Ra\'d',id:'Guruh',type:'Madaniyah',ayat:43},
 {n:14,ar:'ابراهيم',tr:'Ibrahim',id:'Nabi Ibrahim',type:'Makkiyah',ayat:52},
 {n:15,ar:'الحجر',tr:'Al-Hijr',id:'Gunung Hijr',type:'Makkiyah',ayat:99},
 {n:16,ar:'النحل',tr:'An-Nahl',id:'Lebah',type:'Makkiyah',ayat:128},
 {n:17,ar:'الإسراء',tr:'Al-Isra\'',id:'Perjalanan Malam',type:'Makkiyah',ayat:111},
 {n:18,ar:'الكهف',tr:'Al-Kahf',id:'Gua',type:'Makkiyah',ayat:110},
 {n:19,ar:'مريم',tr:'Maryam',id:'Maryam',type:'Makkiyah',ayat:98},
 {n:20,ar:'طه',tr:'Ta-Ha',id:'Ta Ha',type:'Makkiyah',ayat:135},
 {n:21,ar:'الأنبياء',tr:'Al-Anbiya\'',id:'Para Nabi',type:'Makkiyah',ayat:112},
 {n:22,ar:'الحج',tr:'Al-Hajj',id:'Haji',type:'Madaniyah',ayat:78},
 {n:23,ar:'المؤمنون',tr:'Al-Mu\'minun',id:'Orang-Orang Beriman',type:'Makkiyah',ayat:118},
 {n:24,ar:'النور',tr:'An-Nur',id:'Cahaya',type:'Madaniyah',ayat:64},
 {n:25,ar:'الفرقان',tr:'Al-Furqan',id:'Pembeda',type:'Makkiyah',ayat:77},
 {n:26,ar:'الشعراء',tr:'Asy-Syu\'ara\'',id:'Para Penyair',type:'Makkiyah',ayat:227},
 {n:27,ar:'النمل',tr:'An-Naml',id:'Semut',type:'Makkiyah',ayat:93},
 {n:28,ar:'القصص',tr:'Al-Qasas',id:'Kisah',type:'Makkiyah',ayat:88},
 {n:29,ar:'العنكبوت',tr:'Al-\'Ankabut',id:'Laba-Laba',type:'Makkiyah',ayat:69},
 {n:30,ar:'الروم',tr:'Ar-Rum',id:'Bangsa Romawi',type:'Makkiyah',ayat:60},
 {n:31,ar:'لقمان',tr:'Luqman',id:'Luqman',type:'Makkiyah',ayat:34},
 {n:32,ar:'السجدة',tr:'As-Sajdah',id:'Suci',type:'Makkiyah',ayat:30},
 {n:33,ar:'الأحزاب',tr:'Al-Ahzab',id:'Golongan Bersekutu',type:'Madaniyah',ayat:73},
 {n:34,ar:'سبأ',tr:'Saba\'',id:'Kaum Saba\'',type:'Makkiyah',ayat:54},
 {n:35,ar:'فاطر',tr:'Fatir',id:'Pencipta',type:'Makkiyah',ayat:45},
 {n:36,ar:'يس',tr:'Ya-Sin',id:'Ya Sin',type:'Makkiyah',ayat:83},
 {n:37,ar:'الصافات',tr:'As-Saffat',id:'Barisan-barisan',type:'Makkiyah',ayat:182},
 {n:38,ar:'ص',tr:'Sad',id:'Sad',type:'Makkiyah',ayat:88},
 {n:39,ar:'الزمر',tr:'Az-Zumar',id:'Rombongan',type:'Makkiyah',ayat:75},
 {n:40,ar:'غافر',tr:'Ghafir',id:'Pengampun',type:'Makkiyah',ayat:85},
 {n:41,ar:'فصلت',tr:'Fussilat',id:'Yang Dijelaskan',type:'Makkiyah',ayat:54},
 {n:42,ar:'الشورى',tr:'Asy-Syura',id:'Musyawarah',type:'Makkiyah',ayat:53},
 {n:43,ar:'الزخرف',tr:'Az-Zukhruf',id:'Perhiasan',type:'Makkiyah',ayat:89},
 {n:44,ar:'الدخان',tr:'Ad-Dukhan',id:'Asap',type:'Makkiyah',ayat:59},
 {n:45,ar:'الجاثية',tr:'Al-Jathiyah',id:'Berlutut',type:'Makkiyah',ayat:37},
 {n:46,ar:'الأحقاف',tr:'Al-Ahqaf',id:'Bukit Pasir',type:'Makkiyah',ayat:35},
 {n:47,ar:'محمد',tr:'Muhammad',id:'Nabi Muhammad',type:'Madaniyah',ayat:38},
 {n:48,ar:'الفتح',tr:'Al-Fath',id:'Kemenangan',type:'Madaniyah',ayat:29},
 {n:49,ar:'الحجرات',tr:'Al-Hujurat',id:'Kamar-Kamar',type:'Madaniyah',ayat:18},
 {n:50,ar:'ق',tr:'Qaf',id:'Qaf',type:'Makkiyah',ayat:45},
 {n:51,ar:'الذاريات',tr:'Az-Zariyat',id:'Angin yang Menerbangkan',type:'Makkiyah',ayat:60},
 {n:52,ar:'الطور',tr:'At-Tur',id:'Bukit',type:'Makkiyah',ayat:49},
 {n:53,ar:'النجم',tr:'An-Najm',id:'Bintang',type:'Makkiyah',ayat:62},
 {n:54,ar:'القمر',tr:'Al-Qamar',id:'Bulan',type:'Makkiyah',ayat:54},
 {n:55,ar:'الرحمن',tr:'Ar-Rahman',id:'Yang Maha Pemurah',type:'Madaniyah',ayat:78},
 {n:56,ar:'الواقعة',tr:'Al-Waqi\'ah',id:'Hari Kiamat',type:'Makkiyah',ayat:96},
 {n:57,ar:'الحديد',tr:'Al-Hadid',id:'Besi',type:'Madaniyah',ayat:29},
 {n:58,ar:'المجادلة',tr:'Al-Mujadilah',id:'Wanita yang Mengajukan Gugatan',type:'Madaniyah',ayat:22},
 {n:59,ar:'الحشر',tr:'Al-Hasyr',id:'Pengusiran',type:'Madaniyah',ayat:24},
 {n:60,ar:'الممتحنة',tr:'Al-Mumtahanah',id:'Wanita yang Diuji',type:'Madaniyah',ayat:13},
 {n:61,ar:'الصف',tr:'As-Saff',id:'Barisan',type:'Madaniyah',ayat:14},
 {n:62,ar:'الجمعة',tr:'Al-Jumu\'ah',id:'Hari Jumat',type:'Madaniyah',ayat:11},
 {n:63,ar:'المنافقون',tr:'Al-Munafiqun',id:'Orang-Orang Munafik',type:'Madaniyah',ayat:11},
 {n:64,ar:'التغابن',tr:'At-Taghabun',id:'Hari Dinampakkan Kekeliruan',type:'Madaniyah',ayat:18},
 {n:65,ar:'الطلاق',tr:'At-Talaq',id:'Talak',type:'Madaniyah',ayat:12},
 {n:66,ar:'التحريم',tr:'At-Tahrim',id:'Pengharaman',type:'Madaniyah',ayat:12},
 {n:67,ar:'الملك',tr:'Al-Mulk',id:'Kerajaan',type:'Makkiyah',ayat:30},
 {n:68,ar:'القلم',tr:'Al-Qalam',id:'Pena',type:'Makkiyah',ayat:52},
 {n:69,ar:'الحاقة',tr:'Al-Haqqah',id:'Hari Kiamat',type:'Makkiyah',ayat:52},
 {n:70,ar:'المعارج',tr:'Al-Ma\'arij',id:'Tempat-Tempat Naik',type:'Makkiyah',ayat:44},
 {n:71,ar:'نوح',tr:'Nuh',id:'Nabi Nuh',type:'Makkiyah',ayat:28},
 {n:72,ar:'الجن',tr:'Al-Jinn',id:'Jin',type:'Makkiyah',ayat:28},
 {n:73,ar:'المزمل',tr:'Al-Muzzammil',id:'Orang yang Berselimut',type:'Makkiyah',ayat:20},
 {n:74,ar:'المدثر',tr:'Al-Muddaththir',id:'Orang yang Berkemul',type:'Makkiyah',ayat:56},
 {n:75,ar:'القيامة',tr:'Al-Qiyamah',id:'Hari Kiamat',type:'Makkiyah',ayat:40},
 {n:76,ar:'الإنسان',tr:'Al-Insan',id:'Manusia',type:'Madaniyah',ayat:31},
 {n:77,ar:'المرسلات',tr:'Al-Mursalat',id:'Malaikat yang Diutus',type:'Makkiyah',ayat:50},
 {n:78,ar:'النبأ',tr:'An-Naba\'',id:'Berita Besar',type:'Makkiyah',ayat:40},
 {n:79,ar:'النازعات',tr:'An-Nazi\'at',id:'Malaikat yang Mencabut',type:'Makkiyah',ayat:46},
 {n:80,ar:'عبس',tr:'\'Abasa',id:'Ia Bermasam Muka',type:'Makkiyah',ayat:42},
 {n:81,ar:'التكوير',tr:'At-Takwir',id:'Menggulung',type:'Makkiyah',ayat:29},
 {n:82,ar:'الإنفطار',tr:'Al-Infitar',id:'Terbelah',type:'Makkiyah',ayat:19},
 {n:83,ar:'المطففين',tr:'Al-Mutaffifin',id:'Orang-Orang yang Curang',type:'Makkiyah',ayat:36},
 {n:84,ar:'الإنشقاق',tr:'Al-Inshiqaq',id:'Terbelah',type:'Makkiyah',ayat:25},
 {n:85,ar:'البروج',tr:'Al-Buruj',id:'Gugusan Bintang',type:'Makkiyah',ayat:22},
 {n:86,ar:'الطارق',tr:'At-Tariq',id:'Yang Datang di Malam Hari',type:'Makkiyah',ayat:17},
 {n:87,ar:'الأعلى',tr:'Al-A\'la',id:'Yang Paling Tinggi',type:'Makkiyah',ayat:19},
 {n:88,ar:'الغاشية',tr:'Al-Ghashiyah',id:'Hari Pembalasan',type:'Makkiyah',ayat:26},
 {n:89,ar:'الفجر',tr:'Al-Fajr',id:'Fajar',type:'Makkiyah',ayat:30},
 {n:90,ar:'البلد',tr:'Al-Balad',id:'Negeri',type:'Makkiyah',ayat:20},
 {n:91,ar:'الشمس',tr:'Asy-Syams',id:'Matahari',type:'Makkiyah',ayat:15},
 {n:92,ar:'الليل',tr:'Al-Lail',id:'Malam',type:'Makkiyah',ayat:21},
 {n:93,ar:'الضحى',tr:'Ad-Duha',id:'Waktu Dhuha',type:'Makkiyah',ayat:11},
 {n:94,ar:'الشرح',tr:'Al-Insyirah',id:'Kelapangan',type:'Makkiyah',ayat:8},
 {n:95,ar:'التين',tr:'At-Tin',id:'Buah Tin',type:'Makkiyah',ayat:8},
 {n:96,ar:'العلق',tr:'Al-\'Alaq',id:'Segumpal Darah',type:'Makkiyah',ayat:19},
 {n:97,ar:'القدر',tr:'Al-Qadr',id:'Kemuliaan',type:'Makkiyah',ayat:5},
 {n:98,ar:'البينة',tr:'Al-Bayyinah',id:'Bukti yang Nyata',type:'Madaniyah',ayat:8},
 {n:99,ar:'الزلزلة',tr:'Az-Zalzalah',id:'Kegoncangan',type:'Madaniyah',ayat:8},
 {n:100,ar:'العاديات',tr:'Al-\'Adiyat',id:'Kuda yang Berlari Kencang',type:'Makkiyah',ayat:11},
 {n:101,ar:'القارعة',tr:'Al-Qari\'ah',id:'Hari Kiamat',type:'Makkiyah',ayat:11},
 {n:102,ar:'التكاثر',tr:'At-Takathur',id:'Bermegah-megahan',type:'Makkiyah',ayat:8},
 {n:103,ar:'العصر',tr:'Al-\'Asr',id:'Waktu',type:'Makkiyah',ayat:3},
 {n:104,ar:'الهمزة',tr:'Al-Humazah',id:'Pengumpat',type:'Makkiyah',ayat:9},
 {n:105,ar:'الفيل',tr:'Al-Fil',id:'Gajah',type:'Makkiyah',ayat:5},
 {n:106,ar:'قريش',tr:'Quraish',id:'Kaum Quraisy',type:'Makkiyah',ayat:4},
 {n:107,ar:'الماعون',tr:'Al-Ma\'un',id:'Barang-Barang yang Berguna',type:'Makkiyah',ayat:7},
 {n:108,ar:'الكوثر',tr:'Al-Kauthar',id:'Nikmat yang Banyak',type:'Makkiyah',ayat:3},
 {n:109,ar:'الكافرون',tr:'Al-Kafirun',id:'Orang-Orang Kafir',type:'Makkiyah',ayat:6},
 {n:110,ar:'النصر',tr:'An-Nasr',id:'Pertolongan',type:'Madaniyah',ayat:3},
 {n:111,ar:'اللهب',tr:'Al-Lahab',id:'Api yang Bergejolak',type:'Makkiyah',ayat:5},
 {n:112,ar:'الإخلاص',tr:'Al-Ikhlas',id:'Ikhlas',type:'Makkiyah',ayat:4},
 {n:113,ar:'الفلق',tr:'Al-Falaq',id:'Waktu Subuh',type:'Makkiyah',ayat:5},
 {n:114,ar:'الناس',tr:'An-Nas',id:'Manusia',type:'Makkiyah',ayat:6}
];
if (typeof module !== 'undefined') module.exports = SURAHS;
